# Generated by Django 5.1.2 on 2024-10-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requested_inventory', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
